app/main/views.py
from datetime import datetime

from flask import Blueprint, render_template, url_for, redirect, flash, current_app

from app.auth.views import current_user
from app.main.forms import ContactForm
from app.tools import mail

main = Blueprint('main', __name__, template_folder='templates')


@main.route("/")
def home():
    return render_template('home/home.html')


@main.route("/features")
def features():
    return render_template('features/features.html')


@main.route("/contact-us", methods=['GET', 'POST'])
def contact_us():
    form = ContactForm()

    # if the user is authenticated we can
    # add for him some details to makes things faster
    # and easier
    if current_user.is_authenticated():
        form.name.data = current_user.name
        form.email.data = current_user.email

    if form.validate_on_submit():
        subject = f"New support request from {form.email.data} at {datetime.utcnow()}"
        text = str(form)
        to = current_app.config['SUPPORT_CONTACT_EMAIL']
        mail.send_text_message(to, subject, text)
        flash("Thank you for contacting us. We will handle the request as soon as possible.", "success")
        return redirect(url_for('main.contact_us'))
    return render_template('contact-us/contact-us.html',
                           form=form)


@main.route("/activities")
def activities():
    return render_template('activities/activities.html')

app/templates/_error_page.html
{% extends 'base.html' %}
{% set active_page = 'features' %}


{% block title %}Features{% endblock %}

{% block content %}
    <main class="d-flex flex-column justify-content-center align-items-center">
        <div class="custom-container shadow" id="error-container">
            <div class="container-data-wrapper" id="error-wrapper">

                <h2>Uuuuppsss - something went wrong...</h2>
                <p>We see you encountered an error we didn't expect to happen. 😭</p>

                <img alt="A cartoon with a dog and fire everywhere. Source: https://giphy.com/gifs/memecandy-eIfYQTaK3148kmMCxT"
                     class="img-fluid rounded-2"
                     src="{{ url_for('static', filename='images/error-page/error-page.gif') }}">

                <p class="custom-margin-top">Instead of this go to our <a href="{{ url_for('main.home') }}"
                                                                          class="text-decoration-none">main
                    page</a> or come back to us later.</p>

            </div>
        </div>
    </main>
{% endblock %}

app/templates/_flash-messages.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for type, content in messages %}
            <div class="alert alert-{{ type }} alert-dismissible fade show shadow custom-alert" role="alert">
                {{ content }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} - Timely</title>
    <link rel="apple-touch-icon" sizes="180x180"
          href="{{ url_for('static', filename='images/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32"
          href="{{ url_for('static', filename='images/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16"
          href="{{ url_for('static', filename='images/favicon/favicon-16x16.png') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kalam:wght@300&display=swap" rel="stylesheet">
    <link href="{{ url_for('static', filename='styles/main.min.css') }}" rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Timely</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'home' else '' }}" aria-current="page"
                           href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'activities' else '' }}"
                           href="{{ url_for('main.activities') }}">My activities</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'features' else '' }}"
                           href="{{ url_for('main.features') }}">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'contact-us' else '' }}"
                           href="{{ url_for('main.contact_us') }}">Contact us</a>
                    </li>

                    {% if current_user.is_authenticated() %}
                        <li class="nav-item">
                            <a class="nav-link {{ 'active' if active_page == 'account' else '' }}"
                               href="{{ url_for('auth.account') }}">Your account ({{ current_user.name }})</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {{ 'active' if active_page == 'sign-in' else '' }}"
                               href="{{ url_for('auth.login') }}">Sign in</a>
                        </li>
                    {% endif %}


                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="content-wrapper">
    {% block content %}

    {% endblock %}
</div>


<footer class="footer">
    <div class="footer-container">
        <div class="footer-container-entry">
            <h5>About</h5>
            <p>Timely is an free countdown time app. It is accessible on every device<br>
                and platform - you just need a browser to use it.</p>
        </div>
        <div class="footer-container-entry">
            <h5>Quick links</h5>
            <ul class="footer-container-entry-links-list">
                <li><a class="text-decoration-none text-color-black" href="{{ url_for('main.home') }}">Main page</a>
                </li>
                <li><a class="text-decoration-none text-color-black" href="{{ url_for('main.activities') }}">My
                    activities</a>
                </li>
                <li><a class="text-decoration-none text-color-black" href="{{ url_for('main.features') }}">Features</a>
                </li>
                <li><a class="text-decoration-none text-color-black" href="{{ url_for('main.contact_us') }}">Contact
                    us</a></li>
            </ul>
        </div>
        <div class="footer-container-entry">
            <span>            Made with
            <i class="fa fa-heart custom-heart"></i>
             and a lot of
            <i class="fa fa-coffee custom-coffee"></i>
            by
                <a href="https://github.com/tomaszkyc"
                   class="text-decoration-none text-color-black">
                    Tomasz</a>
            </span>
        </div>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://kit.fontawesome.com/24adb84865.js" crossorigin="anonymous"></script>

{% block scripts %}
{% endblock %}
</body>
</html>